#2023.06.20 getResume \uB97C \uD638\uCD9C\uD560 \uB54C \uC774\uBBF8\uC9C0\uC815\uBCF4\uB97C \uBCC0\uD658\uD558\uB294\uB370, \uC774\uB54C \uC11C\uBC84\uB85C\uADF8\uC5D0\uC11C \uBCC0\uD658\uB41C \uC774\uBBF8\uC9C0 \uAC12\uC744 \uBAA8\uB450 \uCD9C\uB825\uD574\uBC84\uB824
#\uAC12\uC774 \uB108\uBB34 \uB9CE\uC774\uB098\uC640 \uC11C\uBC84\uAC00 \uB290\uB824\uC9C0\uB294 \uD604\uC0C1\uC774 \uBC1C\uC0DD\uD558\uC600\uC74C. \uD655\uC778\uACB0\uACFC \uC544\uB798\uC758 \uB85C\uADF8 \uC124\uC815\uC744 TRACE\uB85C \uD558\uBA74 \uBAA8\uB4E0 \uAC12\uC744 \uCD9C\uB825\uD55C\uB2E4
#\uB530\uB77C\uC11C \uC11C\uBC84 \uC131\uB2A5\uC744 \uC704\uD574\uC11C \uACBD\uACE0\uBA54\uC2DC\uC9C0\uB9CC \uCD9C\uB825\uD558\uB3C4\uB85D \uC218\uC815\uD568.


#\uC11C\uBC84\uB85C\uADF8\uB97C \uC804\uBD80\uB2E4 \uCD9C\uB825\uD55C\uB2E4
#logging.level.org.springframework.web: TRACE

#\uC11C\uBC84\uB85C\uADF8\uB97C \uACBD\uACE0\uC5D0 \uD55C\uD574\uC11C\uB9CC \uCD9C\uB825\uD558\uB3C4\uB85D \uD55C\uB2E4
#logging.level.org.springframework.web: WARN
#------------------------------------------------------- \uC704\uB0B4\uC6A9\uC740 applicatiom.properties \uD615\uC2DD

spring:
  profiles:
    active: release
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lifecycle
    username: admin
    password: life12!
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate #개발할 때만 사용. 보통 validate사용
      show-sql : true
      format_sql : true
      naming: #아래 항목을 추가하지않으면 Repositoy에서 테이블명을 지정해주는 대로 DB테이블과 연결하지않고 자동으로 중간중간 언더바 같은걸 넣어버리기때문에 아래 항목을 추가해서 테이블 이름 그대로 사용하도록 함.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  logging:
    level:
      org:
        springframework:
          web: WARN
        hibernate:
          dialect: TRACE
